<?php

namespace WebDreamt;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-28 at 01:00:28.
 */
class BuildTest extends \PHPUnit_Framework_TestCase {

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public static function setUpBeforeClass() {
		Settings::init();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		Build::nuke();
	}

	public function testBuild() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	public function testNuke() {
		$pdo = Settings::pdo();
		$pdo->exec("CREATE TABLE nuke_test (test VARCHAR(20))");
		$this->assertEquals(count($pdo->query("SHOW TABLES")->fetchAll()), 1);
		Build::nuke();
		$this->assertEquals(count($pdo->query("SHOW TABLES")->fetchAll()), 0);
	}

	/**
	 * @covers WebDreamt\Build::updatePropel
	 * @todo   Implement testUpdatePropel().
	 */
	public function testUpdatePropel() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WebDreamt\Build::generateModels
	 * @todo   Implement testGenerateModels().
	 */
	public function testGenerateModels() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WebDreamt\Build::updateDatabase
	 * @todo   Implement testUpdateDatabase().
	 */
	public function testUpdateDatabase() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WebDreamt\Build::generateSchemaXml
	 * @todo   Implement testGenerateSchemaXml().
	 */
	public function testGenerateSchemaXml() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WebDreamt\Build::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
