<?php

namespace WebDreamt;

require_once __DIR__ . '/bootstrap.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-28 at 01:00:29.
 */
class SettingsTest extends \PHPUnit_Framework_TestCase {

	protected function setUp() {

	}

	protected function tearDown() {

	}

	public function testGetDbName() {
		$this->assertEquals("webdreamt", Settings::getDbName());
	}

	public function testGetDbHost() {
		$this->assertEquals("localhost", Settings::getDbHost());
	}

	public function testGetDbUsername() {
		$this->assertEquals("root", Settings::getDbUsername());
	}

	public function testGetDbPassword() {
		$this->assertEquals("", Settings::getDbPassword());
	}

	/**
	 * @covers WebDreamt\Settings::sentry
	 * @todo   Implement testSentry().
	 */
	public function testSentry() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	public function testPdo() {
		$this->assertInstanceOf('\PDO', Settings::pdo());
	}

}
