<?php

namespace WebDreamt;

require_once __DIR__ . '/../../bootstrap.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-28 at 01:00:29.
 */
class SettingsTest extends \PHPUnit_Framework_TestCase {

	protected function setUp() {
		Settings::init();
	}

	protected function tearDown() {

	}

	public function testGetDbName() {
		$this->assertEquals("webdreamt", Settings::getDbName());
	}

	public function testGetDbHost() {
		$this->assertEquals("localhost", Settings::getDbHost());
	}

	public function testGetDbUsername() {
		$this->assertEquals("root", Settings::getDbUsername());
	}

	public function testGetDbPassword() {
		$this->assertEquals("", Settings::getDbPassword());
	}

	public function testSentry() {
		$this->assertInstanceOf('\Cartalyst\Sentry\Sentry', Settings::sentry());
	}

	public function testPdo() {
		$pdo = Settings::pdo();
		$this->assertInstanceOf('\PDO', $pdo);
		$databases = $pdo->query("SHOW DATABASES")->fetchAll(\PDO::FETCH_COLUMN);
		$this->assertContains(Settings::getDbName(), $databases);
		$databases = $pdo->query("SELECT DATABASE()")->fetchAll(\PDO::FETCH_COLUMN);
		$this->assertEquals(Settings::getDbName(), $databases[0]);

//		$pdo = new \PDO("mysql:host=localhost;dbname=webdreamt;charset=utf8", "root", "");
//		$pdo->prepare("CREATE TABLE test (test VARCHAR(20))")->execute();
//		$count = $pdo->query("SHOW TABLES")->fetchAll(\PDO::FETCH_COLUMN);
//		$this->assertEquals(count($count), 1);
	}

}
